### ISSUE TITLE
Synaptic Trackpad doesn't work after sleep

### ISSUE THREAD

**Issue by Flabib** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#11]
Hi, I'm currently using macOS Big Sur 11.2 on IP 320 14-IKB. I have problem when my laptop wake after sleep, trackpad is doesn't work. I use latest open core synaptic version. I hope you can help me to fix this problem.

**Comment by Kni9htKing** [comment]
can u upload ur efi folder without serial somewhere I would like to see it

**Comment by Flabib** [comment]
Sure, this is my EFI's folder.

[EFI.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/5975121/EFI.zip)

**Comment by Kni9htKing** [comment]
Update Your OC to latest version from 0.6.4, and try to use the debug version of synaptic touchpad kext ,For me it works perfect on my elan trackpad.BTW you can use Airport itlwm,it works too. I updated to Big Sur 11.2 yesterday and everything seems fine for me except for bluetooth which connects and disconnects dunno why.

**Comment by Flabib** [comment]
Sorry, I've watch tutorial to update OC and AirportItlwm, but I don't understand so much. May I have your EFI please?

Okay, I'll try AirportItlwm.kext. Thank you.

**Comment by Flabib** [comment]
Oh sorry, I'm forget. I have one more problem, when I plug HDMI, my monitor isn't detect my laptop. Why did this happen?

**Comment by Kni9htKing** [comment]
hey @Flabib 
Here's my EFI - **(Link Removed)**
Note- Use GenSmbios to generate new serial (MacBookPro 14,1)
   I have elan touchpad.
Everything is updated to the latest version as of today.
This Efi Airport itlwm will not work in Catalina (only Big Sur)
Regarding the HDMI output issue ,I haven't tried it yet.    I think its intel graphics problem or kext issue,Dunno .Upload the new efi if you fix HDMI .

**Comment by Flabib** [comment]
I was try using your EFI. HDMI output and Wifi is working fine. But sound over bluetooth connection is laggy. And after sleep, my laptop is going to black screen. I still finding the solution for now.

**Comment by Kni9htKing** [comment]
ya I am unable to fix the bluetooth issue dunno what is causing it ,It connects and disconnects every 1 sec, as a result I have use wired headphones, instead of the bluetooth ones.Do let me if you find it.
As for the black screen issue I am not facing any. You just need to press any key two times after opening the lid .

**Comment by Kni9htKing** [comment]
it will be a great help to u are able to fix bluetooth.
Does bluetooth works fine on your EFI ? ,I haven't tried your EFI So I don't know.
What abt the touchpad did u fix it?

**Comment by Flabib** [comment]
After looking for answers on the forums, I found that bluetooth can work properly when the wifi is off. If I turn on wifi, the signal from bluetooth will weaken.

**Comment by Kni9htKing** [comment]
yup got it .If u fix something else do update me on that.

**Comment by Ab2774** [comment]
Hi @Kni9htKing , I'm really really sorry for the late reply but I've been busy with school and everything, I'm planning for releasing the version in the next few days, I'm having a similar issue with my AX201 on my other laptop, I'm still figuring out how to fix it, I'll keep you updated.
@Flabib can you provide me a copy of IOREG and list all your problems so that I can try to fix them?
Thanks

**Comment by Flabib** [comment]
@Kni9htKing, I accidentally destroy my Mac Volume. I try to fix that but I remove your EFI without have a backup file. Can I have your EFI again please?

@Ab2774, how the way to copy an IOREG?

**Comment by Kni9htKing** [comment]
Here's the efi -- [Efi](https://github.com/Kni9htKing/Lenovo-Ideapad-320-15ikb-Hacintosh)
Use IOREG editor
https://www.google.com/amp/s/mac.filehorse.com/download-ioregistryexplorer/%3famp

**Comment by Flabib** [comment]
I using efi from @Kni9htKing, everything working fine except sleep and bluetooth. When I wake up from sleep, the screen is very slow to respond. Bluetooth is working when I connect to wifi, but signal is weak. If I disconnect from wifi, I can use bluetooth earphone nicely.

[IOReg.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/6044770/IOReg.zip)

**Comment by Ab2774** [comment]
Hi @Flabib, unfortunately, your copy of IOReg seems to be corrupted, please use the latest version which can be found [here](https://github.com/vulgo/IORegistryExplorer/releases/tag/v2.1), but from what you're saying, weak and slow performance can be caused by unworking power management, please make sure that you're using [CpuTscSync](https://github.com/acidanthera/CpuTscSync) as it fixes this problem completely, CPUFriend doesn't fix it, also, make sure that power management is loaded on IOReg with either `CPU0@0` or `PR0@0`, in my case, I have `CPU0@0` if you have the latter, please use this one instead, also, I don't have any update on Intel Bluetooth as it's unstable on macOS, I'll keep you updated.
Cheers
[SSDT-PLUG.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/6047182/SSDT-PLUG.zip)

**Comment by Flabib** [comment]
I have using CpuTscSync and running very well on CPU0@0 and replare with your SSDT-PLUG.. But it still same.

**Comment by tetenc555** [comment]
Hi, I'm having this issue on all versions of VoodooI2C that were released after 2.4.3
Is there any way to solve it? These old versions of kext don't work well with 4 and 3 finger gestures.
