### ISSUE TITLE
macOS Monterey 12 boot long time

### ISSUE THREAD

**Issue by ameenjuz** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#13]
macOS Monterey 12 boot take to long time for coming login screen
Do you have this issue macOS 12

**Comment by Ab2774** [comment]
Hi, yes, I do have this problem too, it's really similar to what happened with Big Sur last year, it took so much effort to install the first Beta and it took so much time to boot, and since it's still the very first Beta that's totally expected, Acidanthera needs to update their kext to work with Monterey, so, just wait a bit and everything will be solved.
Thanks
