### ISSUE TITLE
Your ALCPlugFix + ALC230

### ISSUE THREAD

**Issue by LucasDondo** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#7]
Hi @Ab2774!
**Thank you** so much for solving my issue: I have another laptop but with the same audio codec and if I replug my headphones, then the audio (both input and output) refuses to work for calls (I mean Google Meet, Zoom, Telegram, etc.). The only solution was to restart.
I've been investigating a lot and I **didn't find any solution**. Until I met your guide, saw you had the same codec, watched your repo, saw your ALCPlugFix and finally tried it out... and **the annoying issue was gone**.
So, I want to **propose you** to create a separated repo for this folder, making it **easily available** for all ALC230 users! What do you think about it?
Hope you'll continue contributing to the community!

**Comment by Ab2774** [comment]
Hi, I really appreciate you liking my guide, I have a separate repository for ALCPlugFix [here](https://github.com/Ab2774/ALCPlugFix), I haven't tested it on another Realtek ALCs besides ALC230, since it's the original ALCPlugFix from @goodwin it's old compared to newer systems, I'm gonna try to rebuild it and improve it.
Cheers
